package br.com.pedrohenrique.projetofinal.view;

import android.os.Bundle;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import br.com.pedrohenrique.projetofinal.R;
import br.com.pedrohenrique.projetofinal.controller.SolicitacaoController;
import br.com.pedrohenrique.projetofinal.controller.SuprimentoController;
import br.com.pedrohenrique.projetofinal.model.Solicitacao;
import br.com.pedrohenrique.projetofinal.model.Suprimento;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentSnapshot;

public class SolicitarSuprimentoActivity extends AppCompatActivity {
    private TextView tvSupplyDetails;
    private EditText etNomeSolicitante, etEnderecoSolicitante, etContatoSolicitante;
    private Button btnRequestSupply;
    private SuprimentoController suprimentoController;
    private SolicitacaoController solicitacaoController;
    private Suprimento suprimento;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_solicitar_suprimento);

        tvSupplyDetails = findViewById(R.id.tvSupplyDetails);
        etNomeSolicitante = findViewById(R.id.etNomeSolicitante);
        etEnderecoSolicitante = findViewById(R.id.etEnderecoSolicitante);
        etContatoSolicitante = findViewById(R.id.etContatoSolicitante);
        btnRequestSupply = findViewById(R.id.btnRequestSupply);
        suprimentoController = new SuprimentoController(this);
        solicitacaoController = new SolicitacaoController(this);

        String supplyId = getIntent().getStringExtra("supplyId");
        loadSupplyDetails(supplyId);

        btnRequestSupply.setOnClickListener(view -> {
            String nomeSolicitante = etNomeSolicitante.getText().toString();
            String enderecoSolicitante = etEnderecoSolicitante.getText().toString();
            String contatoSolicitante = etContatoSolicitante.getText().toString();

            if (nomeSolicitante.isEmpty() || enderecoSolicitante.isEmpty() || contatoSolicitante.isEmpty()) {
                Toast.makeText(SolicitarSuprimentoActivity.this, "Por favor, preencha todos os campos.", Toast.LENGTH_SHORT).show();
                return;
            }

            String dataSolicitacao = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new Date());
            String status = "PENDENTE";

            Solicitacao solicitacao = new Solicitacao(
                    null, // UID will be generated by Firestore
                    nomeSolicitante,
                    enderecoSolicitante,
                    contatoSolicitante,
                    supplyId,
                    dataSolicitacao,
                    status
            );

            solicitarSuprimento(solicitacao);
        });
    }

    private void loadSupplyDetails(String supplyId) {
        suprimentoController.consultarSuprimento(supplyId).addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
            @Override
            public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                if (task.isSuccessful()) {
                    suprimento = task.getResult().toObject(Suprimento.class);
                    if (suprimento != null) {
                        tvSupplyDetails.setText("Detalhes do Suprimento: " + suprimento.descricao);
                    }
                } else {
                    Toast.makeText(SolicitarSuprimentoActivity.this, "Erro ao carregar detalhes do suprimento", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }

    private void solicitarSuprimento(Solicitacao solicitacao) {
        solicitacaoController.cadastrarSolicitacao(solicitacao).addOnCompleteListener(task -> {
            if (task.isSuccessful()) {
                Toast.makeText(SolicitarSuprimentoActivity.this, "Solicitação enviada com sucesso", Toast.LENGTH_SHORT).show();
                finish();
            } else {
                Toast.makeText(SolicitarSuprimentoActivity.this, "Erro ao enviar solicitação", Toast.LENGTH_SHORT).show();
            }
        });
    }
}
